export const UNVERIFIED_ID_ON_DELETE = "Отсутствует id. Удаление невозможно"
export const FETCH_TODOS_ERROR = "Ошибка выполнения запроса на получение todos"
export const ADD_TODO_ERROR = "Ошибка добавления todo"
export const DELETE_TODO_ERROR = "Ошибка удаления todo"
export const EDIT_TODO_ERROR = "Ошибка редактирования todo"